import express from 'express';
import bodyParser from 'body-parser';
import ejs from "ejs";

const app = express();
const port = process.env.port || 3000;

app.use(express.static("public"));
app.set("view engine", "ejs");

app.get("/", (req, res) => {
  const index = Math.floor(Math.random() * quotes.length);
  console.log(index);
  const quote = quotes[index];
  res.render("index.ejs", {quote: quote});
});

const quotes = [
  "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
  "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
  "Dream big and dare to fail. – Norman Vaughan",
  "Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs",
  "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
  "Act as if what you do makes a difference. It does. – William James",
  "The best way to predict the future is to create it. – Peter Drucker",
  "Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer",
  "It always seems impossible until it’s done. – Nelson Mandela",
  "Don’t wait. The time will never be just right. – Napoleon Hill",
  "Fall seven times and stand up eight. – Japanese Proverb",
  "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
  "Little by little, one travels far. – J.R.R. Tolkien",
  "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller",
  "Great things are done by a series of small things brought together. – Vincent Van Gogh",
  "The harder the battle, the sweeter the victory.",
  "Energy and persistence conquer all things. – Benjamin Franklin",
  "Push yourself, because no one else is going to do it for you.",
  "Opportunities don’t happen. You create them. – Chris Grosser",
  "Work hard in silence, let your success be your noise. – Frank Ocean",
  "Do one thing every day that scares you. – Eleanor Roosevelt",
  "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Take risks: if you win, you will be happy; if you lose, you will be wise. – Unknown",
  "Courage is resistance to fear, mastery of fear, not absence of fear. – Mark Twain",
  "The secret of getting ahead is getting started. – Mark Twain",
  "Stop waiting for the perfect moment. Take the moment and make it perfect.",
  "If you’re not willing to risk, you’ll always settle for the ordinary.",
  "A year from now you may wish you had started today. – Karen Lamb",
  "Do something today that your future self will thank you for.",
  "Your mindset determines your reality.",
  "Positive anything is better than negative nothing. – Elbert Hubbard",
  "Whether you think you can or you think you can’t, you’re right. – Henry Ford",
  "Happiness is not by chance, but by choice. – Jim Rohn",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. – Winston Churchill",
  "Your life does not get better by chance, it gets better by change. – Jim Rohn",
  "Be so good they can’t ignore you. – Steve Martin",
  "Small progress is still progress.",
  "Believe you can and you’re halfway there. – Theodore Roosevelt",
  "Don’t let yesterday take up too much of today. – Will Rogers",
  "Difficulties in life don’t come to destroy you, but to help you realize your hidden potential.",
  "In the middle of every difficulty lies opportunity. – Albert Einstein",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
  "Strength doesn’t come from what you can do. It comes from overcoming the things you once thought you couldn’t.",
  "When you come to the end of your rope, tie a knot and hang on. – Franklin D. Roosevelt",
  "Obstacles are those frightful things you see when you take your eyes off your goal. – Henry Ford",
  "Failure is simply the opportunity to begin again, this time more intelligently. – Henry Ford",
  "Sometimes adversity is what you need to face in order to become successful. – Zig Ziglar",
  "Don’t let the fear of losing be greater than the excitement of winning. – Robert Kiyosaki",
  "Doubt kills more dreams than failure ever will. – Suzy Kassem",
  "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "The road to success is always under construction. – Lily Tomlin",
  "Don’t aim for success if you want it; just do what you love and believe in, and it will come naturally. – David Frost",
  "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
  "Try not to become a man of success, but rather try to become a man of value. – Albert Einstein",
  "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
  "Work until your idols become your rivals.",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. – Eleanor Roosevelt",
  "Do not be embarrassed by your failures, learn from them and start again. – Richard Branson",
  "Believe in yourself and all that you are. – Christian D. Larson",
  "You are braver than you believe, stronger than you seem, and smarter than you think. – A.A. Milne",
  "Confidence comes not from always being right but from not fearing to be wrong. – Peter T. Mcintyre",
  "Never bend your head. Always hold it high. Look the world straight in the eye. – Helen Keller",
  "You have within you right now, everything you need to deal with whatever the world can throw at you. – Brian Tracy",
  "Don’t let what you cannot do interfere with what you can do. – John Wooden",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. – Ralph Waldo Emerson",
  "I can, therefore I am. – Simone Weil",
  "Be yourself; everyone else is already taken. – Oscar Wilde",
  "Your potential is endless.",
  "Discipline is the bridge between goals and accomplishment. – Jim Rohn",
  "Do what you can, with what you have, where you are. – Theodore Roosevelt",
  "The secret to getting ahead is staying focused.",
  "Success is nothing more than a few simple disciplines, practiced every day. – Jim Rohn",
  "You don’t have to be perfect to be amazing.",
  "The difference between ordinary and extraordinary is that little extra. – Jimmy Johnson",
  "Don’t count the days, make the days count. – Muhammad Ali",
  "Focus on being productive instead of busy. – Tim Ferriss",
  "Don’t let small minds convince you that your dreams are too big. – Unknown",
  "Discipline is choosing between what you want now and what you want most. – Abraham Lincoln",
  "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
  "Do what you love, love what you do, and with all your heart give yourself to it.",
  "Hustle in silence and let your success make the noise.",
  "Sometimes later becomes never. Do it now.",
  "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi",
  "Don’t let the noise of others’ opinions drown out your own inner voice. – Steve Jobs",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "Life is either a daring adventure or nothing at all. – Helen Keller",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
  "Success is liking yourself, liking what you do, and liking how you do it. – Maya Angelou",
  "The struggle you’re in today is developing the strength you need for tomorrow.",
  "Stars can’t shine without darkness. – D.H. Sidebottom",
  "A river cuts through rock not because of its power, but its persistence. – Jim Watkins",
  "Be stronger than your strongest excuse.",
  "Life doesn’t get easier or more forgiving; we get stronger and more resilient. – Steve Maraboli",
  "Turn your wounds into wisdom. – Oprah Winfrey",
  "Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit. – Napoleon Hill",
  "The comeback is always stronger than the setback.",
  "What consumes your mind controls your life.",
  "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman"
]


// const quotes = [
//     "Believe in yourself — you are stronger than you think 💪",
//     "Don’t wait for the perfect moment. Take the moment and make it perfect ✨",
//     "Every great dream begins with a dreamer 🌟",
//     "Keep going. Each step may seem small, but it’s progress ❤️",
//     "Your journey may be tough, but your spirit is tougher 🦋",
//     "The sunrise always follows the darkest night 🌅",
//     "Discipline beats motivation — but motivation makes it beautiful 🌿",
//     "You are capable of more than you imagine 🌈",
//     "Dream big and dare to fail 🌙",
//     "Rise above the storm and you will find the sunshine ☀️",
//     "Don’t stop until you’re proud 🏆",
//     "The harder you work for something, the greater you’ll feel when you achieve it 🌻",
//     "Focus on the step in front of you, not the whole staircase 🪜",
//     "You were born to shine ✨",
//     "Stay positive, work hard, make it happen 💫",
//     "Be your own kind of beautiful 🌹",
//     "When nothing goes right, go left ↩️",
//     "You got this 💪🔥",
//     "Be fearless in the pursuit of what sets your soul on fire ❤️‍🔥",
//     "The best view comes after the hardest climb ⛰️",
//     "Don’t look back — you’re not going that way 🚶‍♀️",
//     "Your time is now ⏰",
//     "Keep your face always toward the sunshine 🌞",
//     "Difficult roads lead to beautiful destinations 🛤️",
//     "Turn your wounds into wisdom 🌺",
//     "You are your only limit 🌠",
//     "Believe you can and you’re halfway there 🚀",
//     "Even the darkest night will end and the sun will rise 🌄",
//     "Don’t be afraid to start over — it’s a new chance to build what you want 🌱",
//     "Progress, not perfection 🌸",
//     "The key to success is to start before you’re ready 🔑",
//     "You are doing better than you think 🌼",
//     "Work hard in silence, let success make the noise 🤫🏅",
//     "Good things take time ⏳",
//     "Stay humble. Work hard. Be kind 🌷",
//     "Let your dreams be bigger than your fears 💭",
//     "Never stop believing in hope 💖",
//     "Failure is not the opposite of success — it’s part of success 🌻",
//     "Small steps every day lead to big results 🐾",
//     "When you can’t find the sunshine, be the sunshine ☀️",
//     "Start where you are. Use what you have. Do what you can 🧭",
//     "Be patient. The best things happen unexpectedly 🎁",
//     "Work while they sleep, dream while they doubt 💼",
//     "The secret of getting ahead is getting started 🏁",
//     "Stay strong. Make them wonder how you’re still smiling 😌",
//     "Be proud of how far you’ve come 🌈",
//     "You don’t have to be perfect to be amazing 💫",
//     "Courage doesn’t always roar — sometimes it’s a quiet whisper 🕊️",
//     "The comeback is always stronger than the setback 💥",
//     "Your vibe attracts your tribe ✨",
//     "The pain you feel today will be the strength you feel tomorrow 🏋️‍♀️",
//     "Don’t let your dreams stay dreams 🌙",
//     "You are made of stardust and magic 🌌",
//     "Focus on progress, not perfection 🪞",
//     "Don’t wish for it, work for it ⚡",
//     "The best way to predict your future is to create it 🌠",
//     "Be brave enough to be bad at something new 🎨",
//     "Turn your can’ts into cans and your dreams into plans 💭➡️📋",
//     "You’re not behind; you’re just on your own path 🛤️",
//     "Don’t wait for opportunity. Create it 🪄",
//     "The struggle you’re in today is developing the strength you need tomorrow 🌿",
//     "Stars can’t shine without darkness 🌟",
//     "Fall seven times, stand up eight 💥",
//     "Push yourself, because no one else is going to do it for you 🦁",
//     "Make today count 📅",
//     "One day or day one — you decide 🕊️",
//     "You didn’t come this far just to come this far 🚶‍♂️",
//     "If you get tired, learn to rest, not to quit 🛏️",
//     "Grow through what you go through 🌻",
//     "Don’t quit. You’re closer than you think 🎯",
//     "A little progress each day adds up to big results 🧩",
//     "Keep believing — the universe is working in your favor 🌌",
//     "You are stronger than your excuses 💪",
//     "Smile — you’re doing your best 😊",
//     "Everything you can imagine is real 🎨",
//     "Never give up on something you can’t go a day without thinking about 💭",
//     "Be the energy you want to attract ⚡",
//     "Your potential is limitless 🚀",
//     "Success starts with self-belief 🌺",
//     "Trust the timing of your life ⏳",
//     "Be proud of every small win 🏅",
//     "The best dreams happen when you’re awake 🌅",
//     "Take the risk or lose the chance 🎯",
//     "The future depends on what you do today 📆",
//     "Focus on the good 💖",
//     "Work hard, stay consistent, be patient 🌱",
//     "Don’t let anyone dull your sparkle 💎",
//     "Prove yourself to yourself, not others 🪞",
//     "A positive mindset brings positive things 🌞",
//     "You’re not lost — you’re finding your way 🌍",
//     "The universe responds to brave souls 🌌",
//     "Every day is a second chance 🌤️",
//     "Keep your heart soft and your mind strong 💗🧠",
//     "You’re growing even when it doesn’t feel like it 🌿",
//     "You are enough. Always were. Always will be 🌸",
//     "The best revenge is massive success 🏆",
//     "Everything happens for a reason — trust the process 🌈",
//     "Be patient — beautiful things take time 💐",
//     "Hustle until your haters ask if you’re hiring 💼",
//     "No rain, no flowers 🌧️🌷",
//     "Stay focused and never give up 🎯",
//     "Dream it. Believe it. Build it 🔨",
//     "The world needs your light 💡",
//     "You’re doing great — keep going 🌻"
//   ];
  
app.listen(port, () => {
    console.log(`Server is running on port ${port}.`);
});